// <auto-generated />
namespace WebBanVeMayBay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EditFieldCCCDtoClientIDinComplainTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditFieldCCCDtoClientIDinComplainTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202112270612196_EditFieldCCCDtoClientIDinComplainTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
